# Generated by Django 4.0.2 on 2022-03-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biorhythm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
