# Generated by Django 4.0.2 on 2022-03-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biorhythm', '0002_remove_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
