# Generated by Django 4.0.2 on 2022-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biorhythm', '0003_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='birthday',
            new_name='date',
        ),
    ]
