# Generated by Django 4.0.2 on 2022-03-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_friends_alter_customuser_birthday'),
        ('user', '0004_alter_customuser_image'),
    ]

    operations = [
    ]
